### ISSUE TITLE
handle large files lookup

### ISSUE THREAD

**Issue by rohit-cribl** [jbeveland27/log-collection-api#1]
Response time suffers when we search on large files. Is there any way to improve/optimize the logic to handle such cases better?

```shell
% curl -o /dev/null -s -w %{time_total}\\n http://localhost:3000/logs/syslog.log/entries/500\?search=8154 
5.043795
```

```shell
% curl -o /dev/null -s -w %{time_total}\\n http://localhost:3000/logs/test.log/entries/500\?search=8154 
0.015114
``` 

```shell
% ls -lh 
total 3766968
-rw-r--r--@ 1 rohit   1.8G 11 Sep 14:20 syslog.log
-rw-r--r--  1 rohit   118K 31 Oct 15:12 test.log
```

**Comment by jbeveland27** [comment]
Hey @rohit-cribl - yeah, I actually have a fix to this locally I did a few days ago and hadn't pushed up yet as I wasn't sure when y'all would be looking at the project. I reversed the logic to read the file starting from the end and moving backwards a character at a time. This alleviates the issue of slow responses as long as the number of entries you're querying for remain relatively low. As I was testing there seemed to be a threshold around 3000 entries where the existing logic took over and was more performant.

I'll push this change up tonight for an additional look. Thanks for taking the time.

**Comment by jbeveland27** [comment]
Hey again @rohit-cribl. I've pushed up changes to address the performance issues with searching large files. I overhauled how it's implemented and added some tests along the way as well. I also addressed some other issues with how configuration of the log directory and UI operate so it should work to have a configurable log directory now.

Here's output when using a 5.6G file:
```bash
» curl -o /dev/null -s -w %{time_total}\\n http://localhost:3000/logs/large_log.log/entries/500
0.015566

» curl -o /dev/null -s -w %{time_total}\\n http://localhost:3000/logs/large_log.log/entries/99999
0.398568

» curl -o /dev/null -s -w %{time_total}\\n http://localhost:3000/logs/large_log.log/entries/99999\?search\=2023
0.360655

» ls -lh /var/log/large_log.log
-rw-r--r--  1 jeveland  wheel   5.6G Oct 18 00:18 /var/log/large_log.log
```

Let me know if you have any other thoughts. Thanks.
